import type { GrammarTask } from "@/types/grammar";

export const sampleTasks: GrammarTask[] = [
  {
    id: "sample-tense-1",
    type: "tense",
    title: "Past Perfect",
    instruction: "Type only the missing verb phrase.",
    prompt: "By the time the meeting started, I ____ the report.",
    context: "Use the verb: finish",
    targetAnswer: "had finished",
    hint: "One action happened before another past action.",
    difficulty: "B1",
  },
  {
    id: "sample-paraphrase-1",
    type: "paraphrase",
    title: "Same Meaning",
    instruction: "Type only the replacement phrase.",
    prompt: "It was too late for us to catch the train. Replace \"too late\" using enough.",
    targetAnswer: "not early enough",
    hint: "Change only the phrase needed to keep the same meaning.",
    difficulty: "B2",
  },
  {
    id: "sample-word-1",
    type: "word_choice",
    title: "Natural Word Choice",
    instruction: "Type only the correct word.",
    prompt: "She made / did a serious mistake in the application.",
    targetAnswer: "made",
    hint: "Some nouns strongly prefer one verb.",
    difficulty: "B1",
  },
  {
    id: "sample-fix-1",
    type: "sentence_fix",
    title: "Sentence Correction",
    instruction: "Type only the corrected phrase.",
    prompt: "He suggested me to apply for the scholarship. Replace \"me to apply\".",
    targetAnswer: "that I apply",
    hint: "After suggest, English usually does not use object + to-infinitive.",
    difficulty: "B2",
  },
  {
    id: "sample-tense-2",
    type: "tense",
    title: "Present Perfect",
    instruction: "Type only the missing verb phrase.",
    prompt: "I ____ three emails so far this morning.",
    context: "Use the verb: send",
    targetAnswer: "have sent",
    hint: "Use present perfect for an action completed before now in an unfinished time period.",
    difficulty: "B1",
  },
  {
    id: "sample-tense-3",
    type: "tense",
    title: "Future Continuous",
    instruction: "Type only the missing verb phrase.",
    prompt: "This time tomorrow, we ____ to Tokyo.",
    context: "Use the verb: fly",
    targetAnswer: "will be flying",
    hint: "Use future continuous for an action in progress at a specific future time.",
    difficulty: "B2",
  },
  {
    id: "sample-paraphrase-2",
    type: "paraphrase",
    title: "Same Meaning",
    instruction: "Type only the replacement phrase.",
    prompt: "Although it was raining, they continued the match. Replace \"Although it was raining\" using despite.",
    context: "Keep the meaning the same.",
    targetAnswer: "Despite the rain",
    hint: "After despite, use a noun phrase or gerund, not a full clause.",
    difficulty: "B2",
  },
  {
    id: "sample-paraphrase-3",
    type: "paraphrase",
    title: "Same Meaning",
    instruction: "Type only the replacement phrase.",
    prompt: "The exam was easier than I expected. Replace \"easier than\" using as.",
    context: "Keep the meaning the same.",
    targetAnswer: "not as difficult as",
    hint: "You may need to change the adjective to keep the same meaning.",
    difficulty: "B2",
  },
  {
    id: "sample-word-2",
    type: "word_choice",
    title: "Natural Word Choice",
    instruction: "Type only the correct word.",
    prompt: "The company raised / rose its prices last month.",
    context: "Choose the transitive verb.",
    targetAnswer: "raised",
    hint: "Raise takes an object; rise does not.",
    difficulty: "B1",
  },
  {
    id: "sample-word-3",
    type: "word_choice",
    title: "Natural Word Choice",
    instruction: "Type only the correct word.",
    prompt: "I need some advice / advise about my presentation.",
    context: "Choose the noun.",
    targetAnswer: "advice",
    hint: "Advice is a noun; advise is a verb.",
    difficulty: "A2",
  },
  {
    id: "sample-vocab-1",
    type: "vocabulary",
    title: "Vocabulary in Context",
    instruction: "Type only the missing word.",
    prompt: "The instructions were so ____ that nobody understood what to do.",
    context: "Use one word meaning unclear or confusing.",
    targetAnswer: "ambiguous",
    hint: "The word describes language with more than one possible meaning.",
    difficulty: "C1",
  },
  {
    id: "sample-vocab-2",
    type: "vocabulary",
    title: "Vocabulary in Context",
    instruction: "Type only the missing word.",
    prompt: "Regular exercise can ____ your mood and energy levels.",
    context: "Use one verb meaning improve.",
    targetAnswer: "boost",
    hint: "This verb is often used with mood, confidence, sales, and energy.",
    difficulty: "B1",
  },
  {
    id: "sample-fix-2",
    type: "sentence_fix",
    title: "Sentence Correction",
    instruction: "Type only the corrected word.",
    prompt: "I am looking forward to meet your team next week. Replace \"meet\".",
    context: "Correct the verb form after the phrase.",
    targetAnswer: "meeting",
    hint: "After looking forward to, use a gerund.",
    difficulty: "B1",
  },
  {
    id: "sample-fix-3",
    type: "sentence_fix",
    title: "Sentence Correction",
    instruction: "Type only the corrected word.",
    prompt: "Neither the manager nor the employees was available. Replace \"was\".",
    context: "Check subject-verb agreement.",
    targetAnswer: "were",
    hint: "With neither/nor, the verb often agrees with the nearer subject.",
    difficulty: "C1",
  },
];
